### ISSUE TITLE
Generating network models 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specnet#1]
@WheezePuppet , you demoed the social network simulation using the following package?

https://github.com/JuliaGraphs/LightGraphs.jl

I am assuming we will first go through 

+ Erdos-Renyi (ER)
+ Scale-free  (SF)
+ Small world (SW) 

The next stage would be to go towards 
+ Configuration models (CM) 
+ Exponential Random Graph Models (ERGM) 
+ Stochastic Block Models (SBM)
+ Latent Block Models (LBM) 

In all the above cases, `igraph` library either via `R` and `python` should be the best way to proceed as the `julia` interface is more of a wish list. 

https://github.com/igraph/igraph/wiki/Julia-interface-to-igraph
 
+ Networks based on manifest homophily, consolidation, and cohesion etc

**Comment by WheezePuppet** [comment]
Great find on the Csardi project! I missed that one in my Google search.

Q: What exactly do you mean by "graphical model representation?"

**Comment by venkatachalapathy** [comment]
Yeah that one's seems more like a wish list because it has a 2015 date on it. Who knows, if we do something with the `cxx` package to import stuff from `igraph`, G might be more be more favourable with his emails! 

Oh! Graphical Models are structured knowledge representations used in both machine learning and statistics to encode, infer uncertain probabilistic knowledge.  It is really useful to visualize probabilistic interactions in large systems, in particular, social networks. 

As I said, not relevant to our project forks, just yet.

**Comment by WheezePuppet** [comment]
> Graphical Models are structured knowledge representations used in both machine learning and statistics to encode, infer uncertain probabilistic knowledge.
Okay, I knew that. I guess what I'm confused about is that it seems like you were saying "graphical models are easily possible in Python and R, but not so easy in Julia." But if "graphical model" means "graphs, aka networks," then it seems to me the LightGraphs package gives us exactly that, just as igraph or networkx might.
I continue to doggedly maintain we won't need Python, R, igraph, or networkx at all. Julia and LightGraphs and StephenCodingMagic will be all we need. (If it turns out I'm wrong about this, I give you permission to shame me publicly.)

**Comment by venkatachalapathy** [comment]
The graphical models I am talking about are probability distributions that are encoded using graphs (and in some contexts, social networks). They are not just graphs. 

There are dedicated graphical model packages in R and some in Python and C++ that are used by the statistics and machine learning communities. But, I agree with you that for the current scope of the project, LightGraphs and StephenCodingMagic will suffice. 

And the beyond part is currently distracting and let us ignore it till we complete this project.

**Comment by WheezePuppet** [comment]
Closing for now as "beyond current scope."
