### ISSUE TITLE
Bibliography here or at PubPub

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specnet#10]
@WheezePuppet , @IngenuityArts and @srikanthmudigonda , 

Do you want to maintain a bibliography of this project fork here or in our PubPub community?

**Comment by srikanthmudigonda** [comment]
Pubpub might be better?

**Comment by WheezePuppet** [comment]
I prefer Zotero for that.

**Comment by venkatachalapathy** [comment]
Could we periodically update PubPub documents from Zotero? This is make things handy as we begin drafting reports.

**Comment by WheezePuppet** [comment]
Sure...what does "update" mean here?

**Comment by venkatachalapathy** [comment]
We started with a basic model inspired by a little bit of historical sociology of Hamilton, CA, a little bit of grid world dynamics; and some wealth inequality thrown in. This would have a specific set of references. 

Now, our project fork is related to the basic model but has our own motivations, both on the modelling front and also not only on the historical sociology front but also on our use of analytical sociology lingo. The references for this iteration is slightly different, right? 

Inspired by your goal of maintaining an up to date version of what the code is doing, I thought why not also provide an up to date reference for why the model is what it is so that we are self-aware of all our changing inspirations as our model themselves evolve/change.

**Comment by WheezePuppet** [comment]
Sure, that sounds good. Zotero can be more of a loosely-organized dumping ground of "all the references we've found along the way," whereas the PubPub page you describe can be a culled version of "the currently active, informative works which we're for sure going to cite in our papers." I like it.

**Comment by venkatachalapathy** [comment]
Good. we are in agreement. I am closing this one and [the other one](https://github.com/IngenuityArts/specscape/issues/5).
