### ISSUE TITLE
Get Rajesh able to run the simulation

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#11]
Figure out whatever OS-specific (or other) issues @venkatachalapathy is facing, and solve them, so he can run the Julia simulation.

**Comment by venkatachalapathy** [comment]
Thanks, Stephen.  We can keep this thread running for this purpose.

**Comment by venkatachalapathy** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/3957017/54061730-fdd5a080-41b6-11e9-8e3d-5d40e1d08de1.png)

So, this is the error I got when I ran your sim.jl

**Comment by venkatachalapathy** [comment]
So, I upgraded julia in my home linux box to the most recent LTS  and tried to run SPECnet code . The code hung on me and I recovered the following messages when I aborted 

    `julia> include("sim.jl")
    [ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
    ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for StatsFuns     [4c63d2b9-4356-54db-8cca-17b64c39e42c]
    │   exception = Required dependency SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] failed to load from a cache file.
    └ @ Base loading.jl:969
    ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for StatsFuns [4c63d2b9-4356-54db-8cca-17b64c39e42c]
    │   exception = Required dependency SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] failed to load from a cache file.
    └ @ Base loading.jl:969
    ┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Contour [d38c429a-6771-53c6-b99e-75d170b6e991]
    │   exception = Required dependency StaticArrays [90137ffa-7385-5640-81b9-e52037218182] failed to load from a cache file.
    └ @ Base loading.jl:969
    ^CERROR: LoadError: InterruptException:
    Stacktrace:
     [1] process_events at ./libuv.jl:98 [inlined]
     [2] wait() at ./event.jl:246
     [3] wait(::Condition) at ./event.jl:46
     [4] stream_wait(::Base.Process, ::Condition) at ./stream.jl:47
     [5] wait at ./process.jl:840 [inlined]
     [6] success at ./process.jl:689 [inlined]
     [7] compilecache(::Base.PkgId, ::String) at ./loading.jl:1195
     [8] _require(::Base.PkgId) at ./loading.jl:960
     [9] require(::Base.PkgId) at ./loading.jl:858
     [10] require(::Module, ::Symbol) at ./loading.jl:853
     [11] include at ./boot.jl:317 [inlined]
     [12] include_relative(::Module, ::String) at ./loading.jl:1044
     [13] include(::Module, ::String) at ./sysimg.jl:29
     [14] include(::String) at ./client.jl:392
     [15] top-level scope at none:0
    in expression starting at /home/rv/cssas/stephen/specnet/src/net/sim.jl:3`

When I run simple code snippets from the documentation, I have no issues. Is this something to do with my prehistoric computer?

**Comment by venkatachalapathy** [comment]
OK, here is a really simple example: 

I created one file test.jl with the following one line statement

    println("hello world")

Then I created another file test2.jl with 

    using test

When I tried to compile test2.jl, it gave the following error

    ERROR: LoadError: ArgumentError: Package test not found in current path:
    - Run `import Pkg; Pkg.add("test")` to install the test package.

and other error messages.  I have stored julia in /opt directory. and have a link in the /urs/local/bin

Should I include the path to the directory in which I am trying to execute test2.jl and test.jl? That seems to be the likely reason.

**Comment by venkatachalapathy** [comment]
On the sim.jl front, I modified the `using` with `include` and ran the simulation. I got the following error message 

    Running sim...
    Using defaults:
    Dict{String,Real} with 6 entries:
      "N" => 40
      "num_iter" => 100
      "max_starting_wealth" => 100
      "proto_threshold" => 50
      "salary_range" => 10
      "openness" => 0.2
    ERROR: LoadError: UndefVarError: pri not defined
    Stacktrace:
     [1] top-level scope at /home/rv/cssas/stephen/specnet/src/net/sim_rv.jl:111
     [2] include at ./boot.jl:317 [inlined]
     [3] include_relative(::Module, ::String) at ./loading.jl:1044
     [4] include(::Module, ::String) at ./sysimg.jl:29
     [5] exec_options(::Base.JLOptions) at ./client.jl:266
     [6] _start() at ./client.jl:425
    in expression starting at /home/rv/cssas/stephen/specnet/src/net/sim_rv.jl:109

**Comment by venkatachalapathy** [comment]
I am closing this issue but hopefully what I've leant is useful for others.

**Comment by WheezePuppet** [comment]
Whew! I'm just now reading all this, and you seem to have had quite a time but solved it all yourself! Is this true? Any outstanding issues remaining?

Btw, the parts I predicted might cause you trouble are the calls to the `run()` function (line 104, and (currently commented out) line 169) which create an OS-level shell and execute a command to it. Pardon if you already know some/all of this, but for completeness:

* The Linux command "`rm -f /path/to/tmp/dir/output*.svg`" cleans up from your system's "`tmp`" directory any old `.svg` files that were used to hold animation images from a previous simulation run, if any.
* The Linux command "`convert -delay 40 /path/to/tmp/dir/output*.svg /path/to/tmp/dir/output.gif`" says to combine all `.svg` files, in filename order, into an animated `.gif` with a 40-millisecond delay between frames.
* The embedded "`$(tempdir())`" part is a Julia thing, substituting the name of your machine's "temp" directory (which on Linux is `/tmp`; God knows where it is on Windows) so that this is in at least one respect OS-independent.

If you don't have the "`convert`" utility on your system (opening a Cygwin shell and typing `convert` is the best way to tell) you'll need to install it or an equivalent to produce the animations.
