### ISSUE TITLE
Remove dead agents from graph entirely

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#12]
Remove dead agents from graph entirely (currently they stay as zombie neighbors).

**Comment by venkatachalapathy** [comment]
Should we reassign this to SPECscape? and retain one here?

**Comment by WheezePuppet** [comment]
Mostly done. A couple caveats:
1. The graph can now become disconnected; for instance, if an agent's only connection to the whole were to die, that agent would then not be part of the giant component anymore. (What to do in this case?)
2. The layout on the animation is no longer consistent frame-to-frame. Will work on this next.

**Comment by venkatachalapathy** [comment]
Regards 1:  It is actually good. There are some graph metrics that discuss how many cuts, a given graph needs to make it disconnected. This aspect will be interesting when we are treating random graphs with giant components. Can the dynamics induce changes not possible in the simple random graph?

**Comment by WheezePuppet** [comment]
Yes, and this seems to model the actual social situation correctly. If you are my only social contact to the rest of the city, and you die (or pack up your bags and leave; whatever the analogous real-world action is to running out of resources), then I am officially disconnected from the city. I would have to form at least one additional social contact to make any inroads.

And by the way, that last refuge is only possible in the simulation when "openness" is greater than 0. If _o_=0 (as it currently is by default) then no disconnected agent has any way of ever making contact with anyone else, and therefore cannot ever join any proto-institution. Sad!

**Comment by WheezePuppet** [comment]
Fixed. Graph plotting is stable, even when agents die, in 7c09a6e.
