### ISSUE TITLE
Create plot of Gini coefficient over time

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#18]
Create plot of Gini coefficient over time.

**Comment by venkatachalapathy** [comment]
Placeholder for @venkatachalapathy to upload documentation on existing R packages that do this and other interesting inequality measures. Also come up with an inequality measure inspired by AS handbook chapter 6.

**Comment by WheezePuppet** [comment]
@will-nehrboss, want to take a crack at this one?

**Comment by will-nehrboss** [comment]
Here's my attempt:

```
#function
function gini(x)
           n = length(x)
               xx = sort(x)
                   2*(sum(collect(1:n).*xx))/(n*sum(xx))-1
                   end
#body
       ginis=[]
#inside iter
      wealthArray=[]

for k in keys(wealths)
     if wealths[k]>=-400
       push!(wealthArray,wealths[k])
	   end
	   end
	   cGini=gini(wealthArray)
	   push!(ginis,cGini)
   #outside Iter
giniPlot=plot(x=1:num_iter,y=ginis, Geom.point, Geom.line, Guide.xlabel("Iteration"), Guide.ylabel("Gini Index"))
draw(PNG("$(tempdir())/GiniPlot.png"), giniPlot)
	   
```
Notes:
Created a wealth array because it was easier and I'm lazy :-)

Before I push this fix to the code base I wanted you @WheezePuppet to take a look and and give me the go ahead.

**Comment by WheezePuppet** [comment]
I like it, although I think @venkatachalapathy and @srikanthmudigonda would probably rather us use R's `ineq` package to do the actual Gini coeff computation.

To do this:
1) Make sure you have R installed.
2) Install the `ineq` package in R. (This can be done via `install.packages("ineq")` at the R command line, at which point it will prompt you for a mirror, just pick one.)
3) In Julia:
```
using RCall
@rlibrary ineq
ineq(wealthArray, type="Gini")```

**Comment by venkatachalapathy** [comment]
As long as we make sure that the code is OK, I don't mind. But this is a good start.

**Comment by will-nehrboss** [comment]
@venkatachalapathy @WheezePuppet  My solution is basically a left hand Riemann approximation of the Lorenz curve (if my lingo is right). The obvious problem is that it will over estimate the gini coefficient, especially with a small dataset of agents. However, with our current # I believe the error rate should be below 3%. You guys know more about what accuracy we need so confer and let me know what you need from my end. I'm perfectly happy to give it another go with rCall, but if that's unnecessary I won't get started.

**Comment by WheezePuppet** [comment]
"another go with rCall" -- I'd forgotten, did you already try to get this working and were unable to?

I just tried it myself and I was astonished at how easy it was. And you can just Julia syntax, just as though you're calling a Julia function, when underlying you're calling an R function instead -- neato! Never seen anything that seamless.
