### ISSUE TITLE
How to use R for statistical analysis from within julia? 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specnet#21]
https://github.com/JuliaInterop/RCall.jl

I know this should go into a roadmap document once things are finalized but am leaving this as an issue until that happens. Also related to #4, #17 and #18.

**Comment by WheezePuppet** [comment]
If plain-old-out-of-the-box Julia can't create a histogram of agent wealth distribution (#17), and/or can't compute a straightforward Gini coefficient and plot it over time (#18), I'll eat my hat.

Not as sure about community detection stuff; that may indeed be something currently only implemented in R, and for which we will need RCall.

**Comment by srikanthmudigonda** [comment]
A somewhat simplistic approach (for now) might be one where we separate the simulation and the associated data-generation steps from data analysis/modeling steps. The former can be done in Julia and the latter in the more mature R set of packages.

**Comment by venkatachalapathy** [comment]
We are going towards a MMA cage match between Sri and Steph! Looking forward to it.

**Comment by srikanthmudigonda** [comment]
hahaha. Let's use Aikido, Stephen, so that we can both pretend to fight and fly through the air using each other's chi/qi force.

**Comment by IngenuityArts** [comment]
In the good old days, an arm wrestling match usually took care of things. Despite many other demands, I have designated tomorrow (Friday) as "Julia Day" which, unlike St. Patrick's Day, lacks its own beverage. However, like the old hedgehog, I will ignore as much as possible and get through some of this: https://julialang.org/learning/ Maybe I'll make up some of these t-shirts for the day.
<img width="443" alt="SPEC back julia cage match" src="https://user-images.githubusercontent.com/47874134/54386510-77660680-466f-11e9-8668-5ff64133d966.PNG">
<img width="443" alt="SPEC front t-shirt" src="https://user-images.githubusercontent.com/47874134/54386515-79c86080-466f-11e9-96fe-5fb6f1e7d0a4.PNG">

**Comment by WheezePuppet** [comment]
?!LOL!?

**Comment by WheezePuppet** [comment]
I'm going to close this issue for now. It should be reopened (or a new one created) if and when there's a specific analysis feature someone wants that we cannot do from within Julia/LightGraphs (which, by the way, at least nominally supports [community detection](http://juliagraphs.github.io/LightGraphs.jl/latest/community.html#Community-Structures-1).)
