### ISSUE TITLE
See whether Jupyter Notebooks solution is worth it

### ISSUE THREAD

**Issue by WheezePuppet** [WheezePuppet/specnet#23]
Create a Notebooks version of SPECnet and host it on caladan. See whether @venkatachalapathy, @IngenuityArts, and others find it usable. If so, spawn other issues to flesh this out, including:
* Make a multi-user version (JupyterHub).
* Encapsulate Julia code in a module (to avoid maintenance issues with having two versions of the sim, one in <tt>.jl</tt> and the other in <tt>.ipynb</tt>).
* Add interactive widgets and such to help the non-coders analyze the sim.

**Comment by IngenuityArts** [comment]
Do some experiments on Stephen's SPECnet notebook in Jupyter to see how it works, how easy to modify or break, etc.

**Comment by WheezePuppet** [comment]
We've decided this is indeed worth it.

The second bullet item, above (encapsulate Julia code in a module) is now complete.

**Comment by WheezePuppet** [comment]
Spawning additional issues (#31, #32), and closing this more general one.
