### ISSUE TITLE
inviting others to this repo 

### ISSUE THREAD

**Issue by venkatachalapathy** [WheezePuppet/specnet#9]
@WheezePuppet , we need to invite Olufemi and Jeffrey to this repo.

**Comment by WheezePuppet** [comment]
Olufemi was invited yesterday (hasn't responded to invitation yet). Jeffrey told me he was somehow erroneously banned from github due to "bad behavior" as soon as he had created an account, and he's now appealing it. Not sure whether there will be criminal charges or not.

**Comment by IngenuityArts** [comment]
I will wait on this before inviting to SPECscape repo. Do you have Olufemi and Jeffrey's github names? Does adding more people put us over the 4 person limit?

**Comment by IngenuityArts** [comment]
I guess "close and comment" is a bit too definitive. I'll re-open and just comment.

**Comment by WheezePuppet** [comment]
Olufemi: Temititayo

Jeff: supposedly jeffg828, but currently getting the account unblocked

And no, there is no limit at all for *public* github repos.

**Comment by IngenuityArts** [comment]
I see the problem. I had SPECscape set to PRIVATE so I couldn't invite any other people. Then I saw you had SPECnet set to public. I've now done that for SPECscape, invited Olufemi, and will wait on Jeff given above: he doesn't show up as a member just now.

**Comment by venkatachalapathy** [comment]
It's time.
